# Generated by Django 5.1.15 on 2026-06-02 17:53

import django.db.models.deletion
import django.utils.timezone
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('MUSIC', 'Music & Concerts'), ('SPORT', 'Sports'), ('MARATHON', 'Marathon & Running'), ('CONFERENCE', 'Conference'), ('THEATRE', 'Theatre & Arts'), ('FESTIVAL', 'Festival'), ('COMEDY', 'Comedy'), ('WORKSHOP', 'Workshop & Training'), ('OTHER', 'Other')], default='MUSIC', max_length=12)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(default='Harare', max_length=80)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event-covers/')),
                ('cover_emoji', models.CharField(default='🎟️', max_length=8)),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold (ZiG)')], default='USD', max_length=3)),
                ('zig_per_usd', models.DecimalField(decimal_places=2, default=30, max_digits=12)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='events.event')),
            ],
            options={
                'ordering': ['order', 'distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=events.models._ref, max_length=16, unique=True)),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks'), ('ZIPIT', 'ZIPIT bank transfer'), ('CARD', 'Visa / Mastercard')], max_length=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold (ZiG)')], default='USD', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=120)),
                ('qr_token', models.CharField(default=events.models._token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('CHECKED_IN', 'Checked in'), ('CANCELLED', 'Cancelled')], default='VALID', max_length=12)),
                ('bib_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chip_id', models.CharField(blank=True, max_length=40)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.order')),
            ],
            options={
                'ordering': ['bib_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('FINISHED', 'Finished'), ('DNF', 'Did not finish'), ('DNS', 'Did not start')], default='REGISTERED', max_length=12)),
                ('gun_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('chip_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('max_per_order', models.PositiveSmallIntegerField(default=10)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['sort', 'price_usd'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype'),
        ),
        migrations.CreateModel(
            name='SplitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='events.checkpoint')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='events.ticket')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('ticket', 'checkpoint')},
            },
        ),
    ]
