# Generated by Django 5.1.15 on 2026-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='poll_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
