# Generated by Django 5.1.15 on 2026-06-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_order_pending_items_order_poll_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks'), ('OMARI', "O'mari"), ('ZIPIT', 'ZimSwitch'), ('CARD', 'Visa / Mastercard')], max_length=12),
        ),
    ]
